In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
n = np.arange(1,21)
result = (2**n)/n
print(result)


[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
i = np.arange(0,6)
print(sum((0.1**(3*i))*0.2**(4*i)))

1.00000160000256


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
M = np.zeros((8,8))
M[1::2,::2] = 1
M[0::2,1::2] = 1
print(M)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
print('X,Y:',X)
ro = np.array((X[:,0]**2+X[:,1]**2)**0.5)
phi = np.arctan(X[:,1]/X[:,0])
result = np.concatenate([[ro],[phi]])
print('ro, phi:',result.reshape(5,2))


X,Y: [[0.73971891 0.64443384]
 [0.12253661 0.03028781]
 [0.36597521 0.8063971 ]
 [0.6912242  0.85357239]
 [0.08520826 0.98303135]]
ro, phi: [[0.98106016 0.1262243 ]
 [0.88555865 1.09835182]
 [0.98671733 0.7166666 ]
 [0.24231672 1.1447537 ]
 [0.89010737 1.48433335]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
print(X)
print(X.argmax()//10, X.argmax()%10)

## your code

[[0.12684615 0.28029118 0.32304691 0.68141109 0.79821325 0.56932843
  0.33442574 0.23227852 0.74784485 0.72961448]
 [0.85634761 0.16137649 0.47838275 0.49795114 0.88532592 0.39626859
  0.3519158  0.38081069 0.45343975 0.28363113]
 [0.09761989 0.62326154 0.90354133 0.13748799 0.79077176 0.73919214
  0.7356994  0.84617291 0.13645066 0.73932558]
 [0.75951776 0.18225891 0.62368734 0.71697668 0.90504849 0.56194821
  0.51867702 0.96369713 0.6321736  0.00644857]
 [0.95369862 0.31755001 0.26870985 0.12635549 0.78849522 0.71417352
  0.34247709 0.72476495 0.63883963 0.16853347]
 [0.67659234 0.92250627 0.79269574 0.30978297 0.83951293 0.29290491
  0.17280303 0.71490037 0.56934466 0.11903803]
 [0.13819817 0.81372849 0.94833415 0.90119684 0.80608894 0.50345929
  0.94710754 0.1977343  0.46880278 0.58705452]
 [0.09078067 0.38296843 0.76642185 0.93323244 0.76886292 0.38890761
  0.32461831 0.19230895 0.46000792 0.00630574]
 [0.51048326 0.37563209 0.57758868 0.74124769 0.94581612 0.68216873
  0.42613712

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
x = X-y
print(X)
r = np.sqrt(x[:,0]**2+x[:,1]**2)
result = X[np.argmin(r)]
print(result)

[[0.10880074 0.2040612 ]
 [0.95063541 0.276219  ]
 [0.26743146 0.05602917]
 [0.17808603 0.74758713]
 [0.91568454 0.3464084 ]
 [0.86132672 0.92164601]
 [0.92685477 0.78645462]
 [0.46908368 0.85756292]
 [0.96407616 0.39020802]
 [0.05517657 0.8579171 ]]
[0.92685477 0.78645462]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
X = np.linspace(-3, 3, 13)
print(X)
result = (X**2+2*X+6)*(X<0)+(X+6)*((X>=0)&(X<=2))+(X**2+4*X-4)*(X>=2)
print(result)

[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
[ 9.    7.25  6.    5.25  5.    5.25  6.    6.5   7.    7.5  16.   12.25
 17.  ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [57]:
X = np.random.random((10, 10))
means = np.expand_dims(np.mean(X, axis=1), axis=1)
result = X-means
check = np.mean(result, axis=1)
print(X)
print(check)

[[8.27692315e-01 2.68165691e-01 1.35768589e-01 2.69864235e-01
  5.01695852e-01 8.36104377e-02 3.68257533e-01 1.34392884e-01
  2.49763532e-01 4.70139314e-01]
 [4.71470281e-02 5.02687905e-01 1.63955980e-01 4.03867577e-01
  2.62170183e-01 6.25614003e-01 1.47965112e-01 7.54149732e-01
  1.45798481e-01 9.87771636e-01]
 [2.02959222e-01 4.01992319e-01 6.26591957e-01 9.60788220e-01
  1.56020653e-01 7.59089294e-01 8.17986692e-01 4.47350403e-01
  6.59979115e-01 3.29674074e-01]
 [3.19908910e-01 4.07235203e-01 3.22274992e-01 4.27630163e-01
  9.53704354e-01 6.22967036e-01 5.75243655e-01 1.35108961e-04
  2.30227970e-01 7.49928731e-01]
 [1.86289115e-01 6.44298572e-01 8.23225477e-01 2.40647690e-01
  9.85605323e-01 6.67072566e-01 2.81816886e-01 6.51114191e-01
  7.51948191e-01 5.55761078e-01]
 [3.43069844e-01 7.67447818e-01 7.82223805e-01 3.84457336e-01
  6.71371454e-01 2.25166126e-02 5.67838064e-01 7.38122676e-01
  4.84928493e-01 8.23253043e-01]
 [7.21243138e-01 1.15914198e-03 2.35884299e-01 9.08421184e

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [52]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(np.mean(X), np.var(X))

5.076231459763676 3.7434569679665746


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [69]:
X = np.arange(5)
Y = np.expand_dims(np.arange(5), axis=1)
result = (X+Y)%5
print(result)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [72]:
X = np.array([50, 3, 1, 7, 20])
c = 5
S = np.arange(len(x))
np.random.choice(S, c, p=X / np.sum(X))

array([4, 0, 4, 0, 4])